mdnsd: add sys/queue.h as required by imsg_init(3)
In file included from log.c:33:
In file included from mdnsd/log.h:24:
In file included from mdnsd/mdnsd.h:30:
/usr/local/include/imsg.h:31:2: error: type name requires a specifier or qualifier
        TAILQ_ENTRY(ibuf)        entry;
        ^
/usr/local/include/imsg.h:31:14: error: a parameter list without types is only allowed in a function
      definition
        TAILQ_ENTRY(ibuf)        entry;
                    ^
/usr/local/include/imsg.h:31:19: error: expected ';' at end of declaration list
        TAILQ_ENTRY(ibuf)        entry;
                         ^
[...]